[[redirects]]
from = "/*"
to = ".netlify/functions/start"
status = 200

[build]
command = "npm install && npm run build:ssr && node server.js"
functions = "netlify/functions/"

[functions]
included_files = ["dist/**"]